alias: Water Reminder
description: ""
triggers:
  - trigger: time_pattern
    hours: /2
conditions:
  - condition: time
    after: "08:00:00"
    before: "18:00:00"
actions:
  - variables:
      files:
        - http://192.168.1.50:8123/local/audio/water_reminder_dinesh_voice.mp3
        - http://192.168.1.50:8123/local/audio/water_reminder_rama_voice.mp3
        - http://192.168.1.50:8123/local/audio/water_reminder_gomathi_voice.mp3
        - http://192.168.1.50:8123/local/audio/water_reminder_sukanya_voice.mp3
      index: "{{ states('input_number.water_voice_index') | int(0) }}"
  - action: script.play_voice_message
    data:
      url: "{{ files[index % (files | length)] }}"
  - action: input_number.set_value
    target:
      entity_id: input_number.water_voice_index
    data:
      value: "{{ (index + 1) % (files | length) }}"
mode: single

